server:
  port: 8085
#数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot-test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&nullCatalogMeansCurrent=true
    username: root
    password: 123456
    druid:
      #初始化大小，最小，最大
      initialSize: 5
      minIdle: 5
      maxActive: 40
      #最大连接等待超时时间
      maxWait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      #配置一个连接在池中的最小生存时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      #打开 PSCache ,并且指定每个连接上 PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      #配置监控统计拦截的 filters 去掉监控界面的 sql将无法统计 ，'wall' 用于防火墙
      filters: stat,wall
      #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      #合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true


# 打印sql
logging:
  level:
    com.java.mapper: debug

########## Mybatis 自身配置 ##########
mybatis-plus:
  # 注意注意
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.mysql.entity
  global-config:
    db-config:
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      #      field-strategy:
      select-strategy: NOT_NULL
      #主键类型
      #实体类主键策略有3种（ 注解 > 全局 > 默认 ）
      #AUTO 数据库ID自增
      #INPUT 用户输入ID
      #ID_WORKER 全局唯一ID，Long类型的主键
      #ID_WORKER_STR 字符串全局唯一ID
      #UUID 全局唯一ID，UUID类型的主键
      #NONE 该类型为未设置主键类型
      id-type: ID_WORKER
      #驼峰下划线转换
      db-column-underline: true
      #表名、是否使用下划线命名，默认数据库表使用下划线命名  true
      table-underline: true
      #刷新mapper 调试神器
      refresh-mapper: true
      #数据库大写下划线转换
      capital-mode: true

  configuration:
    #MyBatis 自动映射时未知列或未知属性处理策略，通过该配置可指定 MyBatis 在自动映射过程中遇到未知
    #NONE：不做任何处理 (默认值)
    #WARNING：以日志的形式打印相关警告信息 .
    #FAILING：当作映射失败处理，并抛出异常和详细信息
    auto-mapping-unknown-column-behavior: failing
    #解决 resultMap 为map时值为空不返回的场景
    call-setters-on-nulls: true



# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: xuzhousuozhiwen
  # 令牌有效期（默认30分钟）
  expireTime: 300



#用于 common.test2 测试
person:
  lastName: lisi
  age: 12
  boss: true
  birth: 2020/11/26

